# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="moe"
#ZSH_THEME="fishy"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git svn)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/bin/:${PATH}"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='vim'
 fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#source ~/.zshrc_aliases
#if [ -e /usr/share/terminfo/x/xterm-256color ] && [ "$COLORTERM" = "xfce4-terminal" ]; then
#    export TERM=xterm-256color
#fi

#if [[ -n "$DISPLAY" && "$TERM" = "xterm" ]]; then
#    export TERM=xterm-256color
#fis

if [ -f /usr/bin/lsb_release ]; then
    DISTRO=$(lsb_release -si)
fi

if [[ $DISTRO = 'Debian' ]]; then
    alias archey='screenfetch'
fi

# Fun / Games
#alias aquarium='asciiquarium'
#alias sudoku='nsudoku'
#alias tetris='bastet'
#alias mario='mupen64plus --windowed ~/ROMs/N64/SuperMario64.v64'
#alias kart='mupen64plus --windowed ~/ROMs/N64/MarioKart64.v64'
#alias zelda='mupen64plus --windowed ~/ROMs/N64/Zelda64.rom'
#alias zeldamajora='mupen64plus --windowed ~/ROMs/N64/ZeldaMajorasMask.z'
#alias ps2='pcsx2'

#System
alias shutdown='sudo shutdown -P now'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias dist-upgrade='sudo apt-get dist-upgrade'
alias autoremove='sudo apt-get autoremove'
alias ainstall='sudo apt-get install'
alias search='sudo apt-cache search'

# Default to human readable figures
alias df='df -h'
alias du='du -h'

# Interactive operation...
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'

# Misc :)
alias less='less -r'                          # raw control characters
alias grep='grep --color'                     # show differences in colour
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour

# Some shortcuts for different directory listings
alias ls='ls -hF --color=auto'                 # classify files in colour
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'
alias k='exit'
alias D='cd ~/Downloads'

## Vim Stuff
alias eV='vim ~/.vim/vimrc'
alias e='vim'

#ZSH Stuff
alias eZ='vim ~/.zshrc'
alias eZA='atom ~/.zshrc'
alias eA='vim ~/.zshrc_aliases'
alias eAA='atom ~/.zshrc_aliases'
alias Z='source ~/.zshrc'

## News and Music
alias news='newsbeuter'
alias nix='cortex linux'
alias twit='turses'

## Net
alias irc='weechat-curses'
alias ST='speedtest-cli'
#alias ssh='TERM=xterm-256color; ssh'
alias mutt='TERM=xterm-256color; mutt'
#alias UM='imapfilter; offlineimap'
alias home='ssh -p 2222 moe@home.comprofix.com'
