# User dependent .bashrc file
# If not running interactively, don't do anything

[[ "$-" != *i* ]] && return

# Various variables you might want for your PS1 prompt instead
Time12h="\T"
Time12a="\@"
PathShort="\w"
PathFull="\W"
NewLine="\n"
Jobs="\j"

# Shell Options
set -o notify
set -o ignoreeof
shopt -s nocaseglob
shopt -s histappend
shopt -s cdspell

# Completion options
COMP_CVS_REMOTE=1
COMP_CONFIGURE_HINTS=1
COMP_TAR_INTERNAL_PATHS=1

[[ -f /etc/bash_completion ]] && . /etc/bash_completion

# Aliases

if [ -f "${HOME}/.bash_aliases" ]; then
   source "${HOME}/.bash_aliases"
fi


if [ -f "${HOME}/.bash_colors" ]; then
   source "${HOME}/.bash_colors"
fi


# Display the current git branch in the command prompt
if [ "$EUID" -ne 0 ]; then
    export PS1="$BWhite[$BGreen\u$BWhite@$BBlue\h $BYellow\w $BWhite]\$ "
else
    export PS1="$BWhite[$BRed\u$BWhite@$BBlue\h $BYellow\w $BWhite]\$ "
fi

if [ -e /usr/share/terminfo/x/xterm-256color ] && [ "$COLORTERM" == "xfce4-terminal" ]; then
    export TERM=xterm-256color
fi

if [[ -n "$DISPLAY" && "$TERM" = "xterm" ]]; then
    export TERM=xterm-256color
fi
